@startuml

package "Accounts Services - producer" as ass{
    (Discovery Service) as disc
    [Banking Library] as lib
    [Bank Account Service] as acc
    lib <.. acc
    acc .> disc : register
}

package "Mobile - consumer"{
    [Mobile Banking Service] as mob
    mob .> disc : register
    acc <-- mob : HTTP
    Mobile_UI -> mob: HTTP
}

package "ATM - consumer"{
    [ATM Service] as atm
    atm .> disc : register
    acc <-- atm: HTTP
    atm <- ATM_UI: HTTP
}

note right of disc
    Service location
    and load balancing
endnote

@enduml